---
#sample_playbook.yml

- name: DISPLAY THE INVENTORY VARS
  # 'all' is top node
  # 'ungrouped' represents devices not assigned to site
  # can also specify sub-sites in DNAC location hierarchy
  hosts: all # all is top node, can also specify sub-sites in DNAC location hierarchy
  gather_facts: no
  tasks:
    - name: DISPLAY THE HOST VARS
      debug:
        msg: "Mgmt host: {{ ansible_host }} platorm: {{ ansible_network_os }}"
      when: ansible_network_os is defined