---
  - name: Ansible CLI Templates
    # hosts: variable can be scoped to DNAC site hierarchy elements
    # such as
    # hosts: all scopes to Global site hierarchy view (ie all devices)
    # hosts: canada scopes to DNAC Site Hierarchy Area called 'canada'
    # hosts: DNA-DC-3850-TCP scopes to DNAC managed device called 'DNA-DC-3850-TCP'
    hosts: DNA-DC-3850-TCP
    connection: local
    gather_facts: false
    vars_files:
      - credentials.yml
    vars:
      dnac_host: "{{dnac_host}}"
      dnac_username: "{{username}}"
      dnac_password: "{{password}}"
      device_name: "{{device_name}}"
      cli_template: "{{cli_template}}"
      dnac_login: &dnac_login
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_version: 2.2.2.3
        dnac_verify: False
        dnac_debug: False

    tasks:
    - name: Get Device Compliance Details
      cisco.dnac.compliance_device_details_info:
        <<: *dnac_login
        deviceUuid: "{{ id }}"
      register: device_compliance

    - name: Display Device Compliance Details
      debug:
        msg: "{{ device_compliance }}"
